### ISSUE TITLE
Compose 

### ISSUE THREAD

**Issue by ZerNox** [Tecnativa/docker-odoo-proxy#1]
Is it possible to provide an example how to start this image since im not able to get it running. 
Did the 
$>docker build . 
Then tried 
>docker run haproxy:1.7-alpine
<7>haproxy-systemd-wrapper: executing /usr/local/sbin/haproxy -p /run/haproxy.pid -db -f /usr/local/etc/haproxy/haproxy.cfg -Ds
[ALERT] 233/074138 (12) : Cannot open configuration file/directory /usr/local/etc/haproxy/haproxy.cfg : No such file or directory
<5>haproxy-systemd-wrapper: exit, haproxy RC=1

**Comment by pedrobaeza** [comment]
The best example is our Doodba scaffolding: https://github.com/Tecnativa/doodba-scaffolding

**Comment by yajo** [comment]
See https://github.com/Tecnativa/doodba#global-inverse-proxy directly.
